### ISSUE TITLE
[FEATURE] Remote Api Service 인터페이스 구현

### ISSUE THREAD

**Issue by Skipancho** [Skipancho/SmartShopping2_app#1]
## 📝  To-do

- [x]  Remote Api Service 인터페이스 구현
- [x]  Remote Api Response 데이터 클래스 구현
- [x]  Remote Api DI Module 구현

## 📆  Date

0913~0913
