### ISSUE TITLE
[FEATURE] 홈  화면 구현

### ISSUE THREAD

**Issue by Skipancho** [Skipancho/SmartShopping2_app#20]
## 📝  To-do

- [x] 상품 목록 관련 Adapter 추가
- [x] 상품 목록 Paging
- [x] 상품 관련 Repository 추가
- [x] 홈화면 UI 구성

## 📆  Date

~
