### ISSUE TITLE
[FEATURE] Local DB 구현

### ISSUE THREAD

**Issue by Skipancho** [Skipancho/SmartShopping2_app#34]
## 📝  To-do

- [x] Room DB 구현 
- [x] DAO 구현
- [x] Local DataSource 구현
- [x] 검색 기록 (SEARCH_HISTORY) table 추가
- [x] 장바구니 table 추가 (이거 근데 로컬 DB 음... 서버에 넣어 버려?)
- [x] 체크리스트 table 추가

## 📆  Date

~
