### ISSUE TITLE
[FEATURE] 구매 기록 분석 화면 구현

### ISSUE THREAD

**Issue by Skipancho** [Skipancho/SmartShopping2_app#60]
## 📝  To-do

- [ ] 구매 기록 분석 화면 UI 구성
- [ ] 구매 기록 카테고리 PieChart 구현
- [ ] 구매 기록 차트 데이터 RecyclerView 구현
