### ISSUE TITLE
[FEATURE] 상품 상세 화면 구현

### ISSUE THREAD

**Issue by Skipancho** [Skipancho/SmartShopping2_app#63]
## 📝  To-do

- [x] 상품 상세 화면 UI 구성
- [x] 상세 화면에서 체크리스트 추가 기능 구현
- [x] 상품 아이템 클릭 시 상세화면으로 이동
