### ISSUE TITLE
[FEATURE] TestCode 작성

### ISSUE THREAD

**Issue by Skipancho** [Skipancho/SmartShopping2_app#64]
## 📝  To-do

- [ ] DataSource 테스트 코드 작성
- [ ] Repository 테스트 코드 작성
- [ ] UseCase 테스트 코드 작성
- [ ]  ...
